version: '3'
services:
    orch-front:
        build: ../orchestrator-frontend-js/.
    orch-auth-service:
        build: ../orchestrator-authentication-service/.
    orch-studio-service:
        build: ../orchestrator-studio-service/.
        volumes:
            - ../orchestrator-studio-service/uploads:/app/uploads
    orch-robot-service:
        build: ../Robot-Microservice-SocketServer/.
    orch-robot-logging-service:
        build: ../orchestrator-robot-logging-service/.
    elasticsearch:
        build: ../orchestrator-elastic-search/.
        ports:
        - 9200:9200
        - 9300:9300
        environment:
        - discovery.type=single-node
        - xpack.security.enabled=false
    keycloak:
        image: quay.io/keycloak/keycloak:21.1.2
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
        ports:
        - 9000:9000
        command: ["start-dev", "--http-port=9000"]
    nginx:
        build: .
        ports:
            - 80:80