version: '3'
services:
    orch-front:
        build: ../orchestrator-frontend/.
    orch-auth-service:
        build: ../orchestrator-authentication-service/.
    orch-studio-service:
        build: ../orchestrator-studio-service/.
        ports:
            - 8001:8000
    nginx:
        build: /.
        ports:
            - 80:80