version: '3'
services:
    orch-front:
        build: ../orchestrator-frontend/.
    orch-auth-service:
        build: ../orchestrator-authentication-service/.
    orch-studio-service:
        build: ../orchestrator-studio-service/.
    orch-robot-logging-service:
        build: ../orchestrator-robot-logging-service/.
    nginx:
        build: .
        ports:
            - 80:80