name: Build

on:
  push:
    branches:
     - master

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  GCE_INSTANCE: ${{ secrets.GCE_INSTANCE }}
  GCE_INSTANCE_ZONE: ${{ secrets.GCE_INSTANCE_ZONE }}

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: "Connect to VM"
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.GCE_HOST }}
        username: ${{ secrets.GCE_USERNAME }}
        key: ${{ secrets.GCE_KEY }}
        script: |
          cd ${{ secrets.GCE_DEPLOYMENT_PATH }}/orchestrator-nginx-gateway && git pull origin master
          sudo docker compose up -d --build nginx